name: "Bump version"

on: 
  push:
    branches: 
     - "master"


jobs: 
  bump-version: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v2 
      - name: 'setup nodejs'
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - name: Git users
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          

      
      
      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/:repository/branches/master/protection
          repository: ${{ github.repository }}
          required_status_checks: |
            null
          enforce_admins: |
            null
          required_pull_request_reviews: |
            null
          restrictions: | 
            null 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Versioning'
        run: |
          npm version patch -m 'update version' 
          git push 
