name: "Bump version"

on: 
  push:
    branches: 
     - "master"


jobs: 
  bump-version: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: 'Update version'
        run: 
          npm version patch -m 'update version'
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Update version"
          git push
        
      - name: "cat package.json"
        run: cat ./package.json
        
        
  
