name: "Bump version"

on: 
  push:
    branches: 
     - "master"


jobs: 
  bump-version: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: 'Commit files'
        run: |
          npm version patch -m 'update version' 
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Add changes"
          git push
      - name: "Push Changes"
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
        
        
  
