name: "Bump version"

on: 
  push:
    branches: 
     - "master"


jobs: 
  bump-version: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v2 
      - name: 'setup nodejs'
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - name: Git users
        run: |
          git config --global user.email "chriscosentino@hotmail.com"
          git config --global user.name "ChrisCosentino"
          
      - name: 'Versioning'
        run: |
          npm version patch -m 'update version' 
      - name: Push to protected branch 
        uses: CasperWA/push-protected@v2
        with: 
          token: ${{ secrets.PUSH_TO_PROTECTED }}
          branch: master
          unprotect_reviews: true
          



