name: "Bump version"

on: 
  push:
    branches: 
     - "master"


jobs: 
  bump-version: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'setup nodejs'
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - name: 'Commit files'
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          npm version patch -m 'update version' 
          git add -A
          git commit -m "Bump version"
          git push
        
        
        
  
